apiVersion: v1
kind: Service
metadata:
  name: devopsg1-k8s-service
spec:
  selector:
    app: devopsg1-k8s-deployment
  type: LoadBalancer 
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 31000